<a href="https://colab.research.google.com/github/Mmmm73/K_means-01/blob/main/k_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
import pandas as pd

In [109]:
ratings=[['John', 5,5,2,1], ['Mary',4,5,3,2], ['Bob', 4,4,4,3], ['Lisa',2,2,4,5], ['Lee',1,2,3,4],['Harry',2,1,5,5]]

In [110]:
ratings

[['John', 5, 5, 2, 1],
 ['Mary', 4, 5, 3, 2],
 ['Bob', 4, 4, 4, 3],
 ['Lisa', 2, 2, 4, 5],
 ['Lee', 1, 2, 3, 4],
 ['Harry', 2, 1, 5, 5]]

In [111]:
type(ratings)

list

In [112]:
ratings[0]

['John', 5, 5, 2, 1]

In [113]:
titles=['User','Jaws','Star Wars','Exorcist','Omen']

In [114]:
titles

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen']

In [115]:
movies=pd.DataFrame(ratings, columns=titles) #create a dataframe

In [119]:
movies

User  Jaws  Star Wars  Exorcist  Omen
0   John     5          5         2     1
1   Mary     4          5         3     2
2    Bob     4          4         4     3
3   Lisa     2          2         4     5
4    Lee     1          2         3     4
5  Harry     2          1         5     5

In [120]:
from sklearn import cluster

In [121]:
data=movies.drop('User', axis=1) #Drop column user from DF

In [122]:
data

Jaws  Star Wars  Exorcist  Omen
0     5          5         2     1
1     4          5         3     2
2     4          4         4     3
3     2          2         4     5
4     1          2         3     4
5     2          1         5     5

In [123]:
#initialization of the Kmeans algorithm.
#n_clusters: number of clusters that the algorithm should try to find.
#max_iter: maximum number of iterations

k_means=cluster.KMeans(n_clusters=2, max_iter=100, random_state=1)

In [124]:
k_means

KMeans(max_iter=100, n_clusters=2, random_state=1)

In [125]:
k_means.fit(data) #Train the model

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(max_iter=100, n_clusters=2, random_state=1)

In [126]:
labels=k_means.labels_

In [128]:
labels

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [129]:
movies

User  Jaws  Star Wars  Exorcist  Omen
0   John     5          5         2     1
1   Mary     4          5         3     2
2    Bob     4          4         4     3
3   Lisa     2          2         4     5
4    Lee     1          2         3     4
5  Harry     2          1         5     5

In [130]:
outcome=pd.DataFrame(labels, index=movies.User, columns=['Cluster ID'])

In [107]:
outcome

Cluster ID
User             
John            1
Mary            1
Bob             1
Lisa            0
Lee             0
Harry           0

In [131]:
k_means.cluster_centers_

array([[1.66666667, 1.66666667, 4.        , 4.66666667],
       [4.33333333, 4.66666667, 3.        , 2.        ]])

In [132]:
import numpy as np


In [133]:
testData=np.array([[4,5,1,2],[3,2,4,4],[3,2,4,1],[3,2,3,3],[5,4,1,4]])

In [134]:
testData

array([[4, 5, 1, 2],
       [3, 2, 4, 4],
       [3, 2, 4, 1],
       [3, 2, 3, 3],
       [5, 4, 1, 4]])

In [135]:
type(testData)

numpy.ndarray

In [136]:
labels_test=k_means.predict(testData)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


In [137]:
labels_test

array([1, 0, 1, 0, 1], dtype=int32)

In [138]:
userNames=np.array(['Maina','Tom','Joyce','Kamau','Otieno']).reshape(-1,1) #reshape list to 2-D array

In [139]:
userNames

array([['Maina'],
       ['Tom'],
       ['Joyce'],
       ['Kamau'],
       ['Otieno']], dtype='<U6')

In [140]:
userNames.reshape(-1,1)

array([['Maina'],
       ['Tom'],
       ['Joyce'],
       ['Kamau'],
       ['Otieno']], dtype='<U6')

In [141]:
userNames

array([['Maina'],
       ['Tom'],
       ['Joyce'],
       ['Kamau'],
       ['Otieno']], dtype='<U6')

In [145]:
labels_test=labels_test.reshape(-1,1) #Reshape array into 2-D array

In [146]:
labels_test

array([[1],
       [0],
       [1],
       [0],
       [1]], dtype=int32)

In [147]:
cols=movies.columns.tolist()

In [149]:
cols

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen']

In [150]:
cols.append('Cluster ID') #Add column 'Cluster ID' to original column list

In [151]:
cols

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen', 'Cluster ID']

In [152]:
newUsers = pd.DataFrame(np.concatenate((userNames, testData,labels_test), axis=1), columns=cols)

In [153]:
newUsers

User Jaws Star Wars Exorcist Omen Cluster ID
0   Maina    4         5        1    2          1
1     Tom    3         2        4    4          0
2   Joyce    3         2        4    1          1
3   Kamau    3         2        3    3          0
4  Otieno    5         4        1    4          1